module.exports = {
    show_files: "show-files",
    add_files: "add-files",
    delete_files: "delete-files",
    show_users: "show-users",
    create_users: "create-users",
    ban_users: "ban-users",
    toggle_admin_users: "toggle-admin-users",
    add_role_users: "add-role-users",
    show_categories: "show-categories",
    edit_categories: "edit-categories",
    delete_categories: "delete-categories",
    add_categories: "add-categories",
    show_roles: "show-roles",
    add_roles: "add-roles",
    delete_roles: "delete-roles",
    edit_roles: "edit-roles",
    show_backups: "show-backups",
    add_backups: "add-backups",
    download_backups: "download-backups",
    restore_backups: "restore-backups",
    show_permissions: "show-permissions",
    edit_permissions: "edit-permissions",
    delete_permissions: "delete-permissions",
    add_permissions: "add-permissions",
};
